{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tarasmap\/trsmapoverayrenderer\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tarasmap\/trsmapoverayrenderer\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapOverayRenderer\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ObjectPoolItem.init()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@TARASMap@objc(cs)TRSMapOverayRenderer(im)init","modules":[{"name":"TARASMap"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapOverayRenderer"]]},"references":{"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapOverayRenderer":{"role":"symbol","title":"TRSMapOverayRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TRSMapOverayRenderer"}],"abstract":[{"type":"text","text":"로봇 지도 위에 오버레이를 그리는 렌더러."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapOverayRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TRSMapOverayRenderer"}],"url":"\/documentation\/tarasmap\/trsmapoverayrenderer"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapOverayRenderer/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapOverayRenderer\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/tarasmap\/trsmapoverayrenderer\/init()"},"doc://kr.co.twinny.taras.map/documentation/TARASMap":{"role":"collection","title":"TARASMap","abstract":[{"type":"text","text":"앱 내에 로봇 지도를 표시하고, 지도 위에 표시될 정보들을 결정합니다."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","kind":"symbol","type":"topic","url":"\/documentation\/tarasmap"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapOverayRenderer\/title","value":"TRSMapOverayRenderer"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapOverayRenderer\/fragments","value":[{"kind":"identifier","text":"TRSMapOverayRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapOverayRenderer~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapOverayRenderer~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}