{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tarasmap\/trsmappoiview\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tarasmap\/trsmappoiview\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init(frame:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"init(frame:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@TARASMap@objc(cs)TRSMapPOIView(im)initWithFrame:","modules":[{"name":"TARASMap"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"hierarchy":{"paths":[["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView"]]},"seeAlsoSections":[{"title":"생성","identifiers":["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init()","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init(coder:)"],"generated":true}],"references":{"doc://kr.co.twinny.taras.map/documentation/TARASMap":{"role":"collection","title":"TARASMap","abstract":[{"type":"text","text":"앱 내에 로봇 지도를 표시하고, 지도 위에 표시될 정보들을 결정합니다."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","kind":"symbol","type":"topic","url":"\/documentation\/tarasmap"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapPOIView":{"role":"symbol","title":"TRSMapPOIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TRSMapPOIView"}],"abstract":[{"type":"text","text":"로봇 지도 위에 표시되는 관심 지점 항목 뷰."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TRSMapPOIView"}],"url":"\/documentation\/tarasmap\/trsmappoiview"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapPOIView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/tarasmap\/trsmappoiview\/init(coder:)"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapPOIView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/tarasmap\/trsmappoiview\/init()"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapPOIView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/tarasmap\/trsmappoiview\/init(frame:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"생성","identifiers":["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init()","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapPOIView\/init(coder:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView\/title","value":"TRSMapPOIView"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView\/fragments","value":[{"kind":"identifier","text":"TRSMapPOIView"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapPOIView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}