{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRequireFailureOf"},{"kind":"text","text":" "},{"kind":"internalParam","text":"otherGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tarasmap\/trsmapview\/gesturerecognizer(_:shouldrequirefailureof:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tarasmap\/trsmapview\/gesturerecognizer(_:shouldrequirefailureof:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/gestureRecognizer(_:shouldRequireFailureOf:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldRequireFailureOf:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRequireFailureOfGestureRecognizer:"}],"role":"symbol","title":"gestureRecognizer(_:shouldRequireFailureOf:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRequireFailureOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@TARASMap@objc(cs)TRSMapView(im)gestureRecognizer:shouldRequireFailureOfGestureRecognizer:","extendedModule":"TARASMap","modules":[{"name":"TARASMap"}]},"hierarchy":{"paths":[["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/UIGestureRecognizerDelegate-Implementations"]]},"references":{"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView":{"role":"symbol","title":"TRSMapView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TRSMapView"}],"abstract":[{"type":"text","text":"로봇 지도와 포함된 항목들을 표시하는 뷰."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TRSMapView"}],"url":"\/documentation\/tarasmap\/trsmapview"},"doc://kr.co.twinny.taras.map/documentation/TARASMap":{"role":"collection","title":"TARASMap","abstract":[{"type":"text","text":"앱 내에 로봇 지도를 표시하고, 지도 위에 표시될 정보들을 결정합니다."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","kind":"symbol","type":"topic","url":"\/documentation\/tarasmap"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/tarasmap\/trsmapview\/uigesturerecognizerdelegate-implementations"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView/gestureRecognizer(_:shouldRequireFailureOf:)":{"role":"symbol","title":"gestureRecognizer(_:shouldRequireFailureOf:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRequireFailureOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/gestureRecognizer(_:shouldRequireFailureOf:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRequireFailureOfGestureRecognizer:"}],"url":"\/documentation\/tarasmap\/trsmapview\/gesturerecognizer(_:shouldrequirefailureof:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizer:shouldRequireFailureOfGestureRecognizer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRequireFailureOfGestureRecognizer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRequireFailureOfGestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"otherGestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView\/title","value":"TRSMapView"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView\/fragments","value":[{"kind":"identifier","text":"TRSMapView"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView~1gestureRecognizer(_:shouldRequireFailureOf:)\/title","value":"gestureRecognizer:shouldRequireFailureOfGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView~1gestureRecognizer(_:shouldRequireFailureOf:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRequireFailureOfGestureRecognizer:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}