{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tarasmap\/trsmapview\/scrollviewwillbegindragging(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tarasmap\/trsmapview\/scrollviewwillbegindragging(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/scrollViewWillBeginDragging(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewWillBeginDragging(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"title":"scrollViewWillBeginDragging(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@TARASMap@objc(cs)TRSMapView(im)scrollViewWillBeginDragging:","modules":[{"name":"TARASMap"}],"navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},"hierarchy":{"paths":[["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/UIScrollViewDelegate-Implementations"]]},"references":{"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView/scrollViewWillBeginDragging(_:)":{"role":"symbol","title":"scrollViewWillBeginDragging(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewWillBeginDragging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/scrollViewWillBeginDragging(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewWillBeginDragging:"}],"url":"\/documentation\/tarasmap\/trsmapview\/scrollviewwillbegindragging(_:)"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView":{"role":"symbol","title":"TRSMapView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TRSMapView"}],"abstract":[{"type":"text","text":"로봇 지도와 포함된 항목들을 표시하는 뷰."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TRSMapView"}],"url":"\/documentation\/tarasmap\/trsmapview"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView/UIScrollViewDelegate-Implementations":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/tarasmap\/trsmapview\/uiscrollviewdelegate-implementations"},"doc://kr.co.twinny.taras.map/documentation/TARASMap":{"role":"collection","title":"TARASMap","abstract":[{"type":"text","text":"앱 내에 로봇 지도를 표시하고, 지도 위에 표시될 정보들을 결정합니다."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","kind":"symbol","type":"topic","url":"\/documentation\/tarasmap"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView~1scrollViewWillBeginDragging(_:)\/title","value":"scrollViewWillBeginDragging:"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView~1scrollViewWillBeginDragging(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewWillBeginDragging:"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView\/title","value":"TRSMapView"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView\/fragments","value":[{"kind":"identifier","text":"TRSMapView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}