{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previousTraitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tarasmap\/trsmapview\/traitcollectiondidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tarasmap\/trsmapview\/traitcollectiondidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/traitCollectionDidChange(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"title":"traitCollectionDidChange(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TARASMap@objc(cs)TRSMapView(im)traitCollectionDidChange:","modules":[{"name":"TARASMap"}],"navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}]},"hierarchy":{"paths":[["doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView"]]},"references":{"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView/traitCollectionDidChange(_:)":{"role":"symbol","title":"traitCollectionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView\/traitCollectionDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"url":"\/documentation\/tarasmap\/trsmapview\/traitcollectiondidchange(_:)"},"doc://kr.co.twinny.taras.map/documentation/TARASMap/TRSMapView":{"role":"symbol","title":"TRSMapView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TRSMapView"}],"abstract":[{"type":"text","text":"로봇 지도와 포함된 항목들을 표시하는 뷰."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap\/TRSMapView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TRSMapView"}],"url":"\/documentation\/tarasmap\/trsmapview"},"doc://kr.co.twinny.taras.map/documentation/TARASMap":{"role":"collection","title":"TARASMap","abstract":[{"type":"text","text":"앱 내에 로봇 지도를 표시하고, 지도 위에 표시될 정보들을 결정합니다."}],"identifier":"doc:\/\/kr.co.twinny.taras.map\/documentation\/TARASMap","kind":"symbol","type":"topic","url":"\/documentation\/tarasmap"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"traitCollectionDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"previousTraitCollection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView\/title","value":"TRSMapView"},{"op":"replace","path":"\/references\/doc:~1~1kr.co.twinny.taras.map~1documentation~1TARASMap~1TRSMapView\/fragments","value":[{"kind":"identifier","text":"TRSMapView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}